import { Sidebar } from '@/components/Sidebar'
import { MainNav } from '@/components/main-nav'
import { Search } from '@/components/search'
import TeamSwitcher from '@/components/team-switcher'
import { UserNav } from '@/components/user-nav'
import '@/styles/globals.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="border-b">
          <div className="flex h-20 items-center px-4">
            <div className="relative z-20 flex items-center text-lg font-medium ml-3">
              <Image 
                src={"/Zooma_Mug.png"}
                width={70}
                height={70}
                alt="Zooma"
                className='mr-2 cursor-pointer'
              />
            </div>
            <div className="ml-auto flex items-center space-x-4">
              <Search />
              <UserNav />
            </div>
          </div>
        </div>
        <section className='grid lg:grid-cols-5'>
          <Sidebar className="hidden lg:block"/>
          <div className='col-span-3 lg:col-span-4 lg:border-l'>
            {children}
          </div>
        </section>
      </body>
    </html>
  )
}
